In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
print(torch.__version__)

2.4.1+cu121


# Introduction to Tensors

creating Tensor

In [ ]:
# Scaler

scaler = torch.tensor(7)
scaler

tensor(7)

In [ ]:
scaler.ndim

0

In [ ]:
# vector

vector= torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix

Matrix=torch.tensor([[7,8],[9,10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
Matrix.ndim

2

In [ ]:
Matrix[0]

tensor([7, 8])

In [ ]:
Matrix[1]

tensor([ 9, 10])

In [ ]:
Matrix.shape

torch.Size([2, 2])

In [ ]:
# tenser
tensor=torch.tensor([[[1,2,3],[2,4,5],[6,7,8]]])
tensor

tensor([[[1, 2, 3],
         [2, 4, 5],
         [6, 7, 8]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

# Random Tensor

In [ ]:
random_tensor = torch.rand(3,4)

In [ ]:
random_tensor

tensor([[0.8751, 0.4789, 0.6935, 0.0265],
        [0.5623, 0.9521, 0.4083, 0.0548],
        [0.5759, 0.3718, 0.2234, 0.6170]])

In [ ]:
torch.rand(3,3)

tensor([[0.6737, 0.7784, 0.7657],
        [0.7395, 0.5793, 0.0958],
        [0.5229, 0.4830, 0.7211]])

In [ ]:
zeros = torch.zeros(size=(3,4))

In [ ]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones= torch.ones(size=(3,4))

In [ ]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [3]:
torch.range(0,10)

<ipython-input-3-dfdec9b83f7d>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [4]:
one_to_ten=torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#manipulating Tensor
# Addition
# Subtraction
# Multiplication(element wise)
# DIvidation
# Matrix Multiplication


In [8]:
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [7]:
tensor*10

100

In [9]:
tensor-10

tensor([-9, -8, -7])

In [10]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [11]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [ ]:
# Matrix multiplication
# Inner dimensions must match:
# (3,2) @ (3,2)--- won't work
# (3,2) @ (2,3)--- will work
# (2,3) @ (3,2)--- will work


In [12]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.6988, 0.1415],
        [1.0619, 0.3005]])

In [13]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.0458, 0.4655, 0.0442],
        [0.0445, 0.2803, 0.0442],
        [0.1378, 0.7231, 0.1379]])

In [ ]:
# Tensor Aggregation (max,min,sum,mean,etc)


In [17]:
# Create Aggregate
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [18]:
# find the min
torch.min(x)

tensor(0)

In [19]:
x.min()

tensor(0)

In [20]:
# find the max
torch.max(x)

tensor(90)

In [22]:
x.max()

tensor(90)

In [23]:
# find mean
torch.mean(x.type(torch.float32))

tensor(45.)

In [24]:
x.type(torch.float32).mean()

tensor(45.)

In [25]:
#find the sum
torch.sum(x)


tensor(450)

In [26]:
x.sum()

tensor(450)

In [27]:
# finding the positional min & max
x.argmin()

tensor(0)

In [29]:
x.argmax()

tensor(9)

# Reshaping

In [30]:
# Lets Create a tensor
import torch
x=torch.arange(1.,10.)
x,x.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [31]:
# Add an extra Dimention
x_reshaped=x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [32]:
# view
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [33]:
# changing Z changes x
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [36]:
x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [37]:
# torch.squeeze(). remove all single dimensions from a target tensor
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [38]:
x_reshaped.shape

torch.Size([1, 9])

In [39]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [40]:
x_reshaped.squeeze().shape

torch.Size([9])