In [ ]:
%tensorflow_version 2.x


Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [2]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [ ]:
tf.__version__

'2.17.0'

In [ ]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

In [ ]:
x=tf.constant(10)
x


<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
x=tf.constant(10.5)
x

<tf.Tensor: shape=(), dtype=float32, numpy=10.5>

In [ ]:
y=tf.constant('India')
y

<tf.Tensor: shape=(), dtype=string, numpy=b'India'>

In [ ]:
t=tf.constant([1,2,3,4,5])
t

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [ ]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
tf.constant(a)

<tf.Tensor: shape=(2, 4), dtype=int64, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])>

In [ ]:
t_2d=tf.constant([[1,2],[3,4]])
t_2d

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
t_1d=tf.constant([1,2,3,4])
t_1d

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
t_2d_1=tf.constant([1,2,3,4],shape=(2,2),dtype='int32')
t_2d_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
t_3d_1=tf.constant([[[1,2],[2,3],[3,4]]],dtype='float32')
t_3d_1

<tf.Tensor: shape=(1, 3, 2), dtype=float32, numpy=
array([[[1., 2.],
        [2., 3.],
        [3., 4.]]], dtype=float32)>

In [ ]:
type(t_3d_1)

tensorflow.python.framework.ops.EagerTensor



---



In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
a=10
b=9

In [ ]:
tf.add(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=19>

In [ ]:
# Addition two list

l1=[1,2,3,4,5]
l2=[6,7,8,9,2]
tf.add(l1,l2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 7,  9, 11, 13,  7], dtype=int32)>

In [3]:
l1=[[1,2],[3,4]]
l2=[[6,7],[8,9]]
tf.add(l1,l2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7,  9],
       [11, 13]], dtype=int32)>

In [ ]:
l1=[1,2,3,4,5]
l2=[6,7,8,9,2]
tf.add(l1,l2)

In [ ]:
l1=[1,2,3,4]
a=10
tf.add(l1,a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([11, 12, 13, 14], dtype=int32)>

In [ ]:
# Give a tensor x and a tensor y, this operation x*y computers for corresponding elements in x and y.

x=tf.constant([[2,2],[3,3]])
y=tf.constant([[8,16],[2,3]])
tf.pow(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]], dtype=int32)>

In [ ]:
# complex number
x=tf.constant([[-2.25 + 4.75j],[-3.25 + 5.75j]])
tf.abs(x)

<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[5.25594901],
       [6.60492241]])>

In [ ]:
# tf.math.subtract
x=[1,2,3,4,5]
a=1
tf.subtract(x,a)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>

In [ ]:
x=[1,2,3,4,5]
a=1
tf.subtract(a,x)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 0, -1, -2, -3, -4], dtype=int32)>

In [ ]:
# tf.multiply
x=tf.constant(([1,2,3,4]))
tf.multiply(x,x)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 1,  4,  9, 16], dtype=int32)>

In [ ]:
tf.multiply(7,6)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [ ]:
x=tf.ones([1,2])
y=tf.ones([2,1])
x*y

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [ ]:
# tf.maximum
x=tf.constant([0.,0.,0.,0.])
y=tf.constant([-2.,0.,2.,5.])
tf.maximum(x,y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 2., 5.], dtype=float32)>

In [ ]:
x=tf.constant([-5.,0.,0.,0.])
y=tf.constant([-3.])
tf.maximum(x,y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-3.,  0.,  0.,  0.], dtype=float32)>

In [ ]:
# tf.minimum
x=tf.constant([0.,0.,0.,0.])
y=tf.constant([-5.,0.,-2.,5.])
tf.minimum(x,y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-5.,  0., -2.,  0.], dtype=float32)>

In [ ]:
x=tf.constant([-5.,0.,0.,0.])
y=tf.constant([-3.])
tf.minimum(x,y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-5., -3., -3., -3.], dtype=float32)>

In [ ]:
# tf.divide
x=tf.constant([16,12,11])
y=tf.constant([4,6,2])
tf.divide(x,y)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([4. , 2. , 5.5])>

In [ ]:
# tf.pow
x=tf.constant([[2,2],[3,3]])
y=tf.constant([[8,16],[2,3]])
tf.pow(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]], dtype=int32)>

In [ ]:
# tf.sqrt
x=tf.constant([[4.0],[16.0]])
tf.sqrt(x)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [4.]], dtype=float32)>

In [ ]:
# tf.sqrt
y=tf.constant([[-4.0],[16.0]])
tf.sqrt(y)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[nan],
       [ 4.]], dtype=float32)>

In [ ]:
tf.ones(1)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [ ]:
tf.ones((1)),tf.float32

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>,
 tf.float32)

In [ ]:
ones_2d= tf.ones((2,2)),tf.float32
ones_2d

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.]], dtype=float32)>,
 tf.float32)

In [ ]:
ones_3d=tf.ones((2,2,4),tf.float32)
ones_3d

<tf.Tensor: shape=(2, 2, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [ ]:
tf.zeros(1)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>

In [ ]:
zeros_2d=tf.zeros((2,2),tf.int32)
zeros_2d

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0]], dtype=int32)>

In [ ]:
zeros_3d=tf.zeros((2,2,4),tf.int32)
zeros_3d

<tf.Tensor: shape=(2, 2, 4), dtype=int32, numpy=
array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)>

# Tensorflow  Variable

Variable constructor requires an initial value for the variable which can be a tensor of any type & shape


In [ ]:
# Variable constructor requires an initial value for the variable which can be a tensor of any type & shape
# this initial value defines the type of& shape of the variable.
# After

In [ ]:
import tensorflow as tf

In [ ]:
tf.Variable(1)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [ ]:
x=tf.Variable([1,2,3,4])
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
x.name

'Variable:0'

In [ ]:
x.shape

TensorShape([4])

In [ ]:
x.dtype

tf.int32

In [ ]:
y=tf.Variable([1.0,2,3,4])

In [ ]:
y

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>

In [ ]:
z=tf.Variable(True, False)
z

<tf.Variable 'Variable:0' shape=() dtype=bool, numpy=True>

In [ ]:
t_con=tf.constant([1,2,3,4])

In [ ]:
t_con

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
tf.Variable(t_con)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

# Create Tensorflow variable with different Shape

In [ ]:
t_2d=tf.Variable([[1,2],[4,5]])
t_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [4, 5]], dtype=int32)>

In [ ]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
tf.reshape(x,(2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
# get index in high value

In [ ]:
t_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [4, 5]], dtype=int32)>

In [ ]:
tf.argmax(t_2d)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1])>

In [ ]:
# viewed/Convert as a tensor

In [ ]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
tf.convert_to_tensor(x)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
tf.convert_to_tensor(t_2d)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5]], dtype=int32)>

In [ ]:
# change/assign new value to tensor

In [ ]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
x.assign([4,6,2,8])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([4, 6, 2, 8], dtype=int32)>

In [ ]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([4, 6, 2, 8], dtype=int32)>

In [ ]:
x.assign([4,6,2,9])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([4, 6, 2, 9], dtype=int32)>

In [ ]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([4, 6, 2, 9], dtype=int32)>

In [ ]:
# assign variable with another memory

In [ ]:
x.assign_add([4,6,2,8])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([ 8, 12,  4, 17], dtype=int32)>

In [ ]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([ 8, 12,  4, 17], dtype=int32)>

# Placeholder-Migrate tensorflow 1 code to tensorflow 2

Place holder is a vriable that we will assign data to at a later date.

In [ ]:
import tensorflow as tf

In [ ]:
tf.placeholder(dtype.float32,shape=(400,400))

AttributeError: module 'tensorflow' has no attribute 'placeholder'

In [ ]:
tf.compat.v1.disable_eager_execution()

In [ ]:
tf.compat.v1.placeholder(dtype=tf.float32,shape=(400,400))

<tf.Tensor 'Placeholder:0' shape=(400, 400) dtype=float32>

In [ ]:
a=tf.compat.v1.placeholder(dtype=tf.float32,shape=(400,400))
a

<tf.Tensor 'Placeholder_2:0' shape=(400, 400) dtype=float32>

In [ ]:
b=tf.compat.v1.placeholder(dtype=tf.float32,shape=(400,400))
b

<tf.Tensor 'Placeholder_3:0' shape=(400, 400) dtype=float32>

In [ ]:
c=tf.add(a,b)
c

<tf.Tensor 'Add:0' shape=(400, 400) dtype=float32>

In [ ]:
import numpy as np

In [ ]:
ones_array=np.ones((400,400),np.float32)
ones_array

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], dtype=float32)

In [ ]:
with tf.compat.v1.Session() as sess:
  d=sess.run(c,feed_dict={a:ones_array,b:ones_array})

In [ ]:
d

array([[2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       ...,
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.]], dtype=float32)

# Sparse tensor

it enables efficient storage & processing of tensors that contains lots of zero values.

In [ ]:
tf.SparseTensor()

TypeError: SparseTensor.__init__() missing 3 required positional arguments: 'indices', 'values', and 'dense_shape'

In [ ]:
tf.SparseTensor(indices=[[0,3],[2,4]],values=[10,20],dense_shape=[3,10])

SparseTensor(indices=Tensor("SparseTensor/indices:0", shape=(2, 2), dtype=int64), values=Tensor("SparseTensor/values:0", shape=(2,), dtype=int32), dense_shape=Tensor("SparseTensor/dense_shape:0", shape=(2,), dtype=int64))

In [ ]:
st1=tf.SparseTensor(indices=[[0,3],[2,4]],values=[10,20],dense_shape=[3,10])
st1

SparseTensor(indices=Tensor("SparseTensor_1/indices:0", shape=(2, 2), dtype=int64), values=Tensor("SparseTensor_1/values:0", shape=(2,), dtype=int32), dense_shape=Tensor("SparseTensor_1/dense_shape:0", shape=(2,), dtype=int64))

In [ ]:
print(st1)

SparseTensor(indices=Tensor("SparseTensor_1/indices:0", shape=(2, 2), dtype=int64), values=Tensor("SparseTensor_1/values:0", shape=(2,), dtype=int32), dense_shape=Tensor("SparseTensor_1/dense_shape:0", shape=(2,), dtype=int64))


tensor flow graf

In [4]:
import tensorflow as tf

x=tf.compat.v1.get_variable('x',dtype=tf.int32, initializer=tf.constant([5]))
y=tf.compat.v1.get_variable('y',dtype=tf.int32, initializer=tf.constant([6]))

In [5]:
c=tf.constant([5],name='constant')
square=tf.constant([2],name='square')
f = tf.multiply(x,y) + tf.pow(x,square) + y + c
f

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([66], dtype=int32)>